[package]
name = "opera"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
raylib = "5.5.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
